@startuml
'https://plantuml.com/sequence-diagram

skinparam ParticipantFontStyle bold
skinparam DatabaseFontStyle bold
skinparam CollectionsFontStyle bold
skinparam BackgroundColor White
skinparam TitleFontSize 25
skinparam TitleFontStyle bold
autonumber "<font color=blue><b>"

title FX Heatmap Strategy

database "YFinance API" #720E9E
participant DataLoader #White
database "Local data" #SteelBlue
participant DataProcessor #White
participant HeatmapBuilder #White
database Images #FireBrick
participant ThermalVision #White
database Model #GoldenRod
participant BackTest #White

group Data Pipeline
'DataLoader sequence
    group #LightBlue DataLoader
        DataLoader -> DataLoader: Initialise
        activate DataLoader #LightSlateGrey
        DataLoader <-> "YFinance API": Download data
        DataLoader -> "Local data": Store raw data
        deactivate
    end

'DataProcessor sequence
    group #LightBlue DataProcessor
        DataProcessor -> DataProcessor: Initialise
        activate DataProcessor #LightSlateGrey
        DataProcessor <-> "Local data": Load data
        DataProcessor -> DataProcessor: Build USD\nregimes
        DataProcessor -> DataProcessor: Build currency\nfeatures
        DataProcessor -> "Local data": Store processed\ndata
        deactivate
    end

'HeatmapBuilder sequence
    group #LightBlue HeatmapBuilder
        HeatmapBuilder -> HeatmapBuilder: Initialise
        activate HeatmapBuilder #LightSlateGrey
        HeatmapBuilder <-> "Local data": Load processed data
        HeatmapBuilder -> HeatmapBuilder: Building feature matrices
        HeatmapBuilder -> "Local data": Store matrices
        HeatmapBuilder -> HeatmapBuilder: Build heatmaps
        HeatmapBuilder -> Images: Store heatmaps
        deactivate
    end
end

group Strategy Pipeline
'ThermalVision sequence
    group #LightBlue ThermalVision
        ThermalVision -> ThermalVision: Initialise
        activate ThermalVision #LightSlateGrey
        ThermalVision <-> Images: Load Heatmaps
        ThermalVision -> ThermalVision: Compile and Train CNN
        ThermalVision -> Model: Save CNN
        deactivate
    end

'Backtest sequence
    group #LightBlue BackTest
        BackTest -> BackTest: Initialise
        activate BackTest #LightSlateGrey
        BackTest <-> Model: Load model
        BackTest -> BackTest: Backtest strategy
        BackTest -> Images: Save results
        deactivate
    end
end

@enduml
